### ISSUE TITLE
Fix toast position on login

### ISSUE THREAD

**Issue by emroussel** [emroussel/stockpile-app#208]
It shows under the keyboard when it is focused on password field, so user doesn't get feedback

**Comment by emmanuelroussel** [comment]
@AdamVig what problem did you experience with this exactly? On my Android phone, the toast shows over the keyboard like expected.

**Comment by AdamVig** [comment]
On my iPhone, it displayed underneath the keyboard.

**Comment by emroussel** [comment]
This is probably related to #218

**Comment by emroussel** [comment]
Actually cannot reproduce, might be a problem with Ionic View and will be confirmed with further testing in #218 when the app is published to the app stores.
