### ISSUE TITLE
Fix missing info.plist key

### ISSUE THREAD

**Issue by AdamVig** [emroussel/stockpile-app#282]
When uploading the archived app binary to iTunes Connect, the following error was emailed to me:
> Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app’s Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by emroussel** [comment]
@AdamVig the solution seems to add: `<string>Used to scan barccodes</string>` on the line under `<key>NSCameraUsageDescription</key>` in  `./platforms/ios/Stockpile/Stockpile-info.plist`. There should be a way to add it automatically when you run `ionic platform add ios`, but I can't easily find an answer online. I will keep looking, but you can use the temporary solution above for now if you want.
